version: 2
updates:
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      pytorch:
        patterns:
          - torch
          - torchvision
